In [8]:
a = [1,1,2,3]
b = [1,1,2,3]
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])
c


[1, 1, 4, 9]

In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
a
# shape means dimension /weidu
a.shape
# array shape zhou de ge shu
a.ndim
# 2
a.dtype.name
# int 32
a.itemsize
#4
a.size
# 15
type(a)
# numpy.ndarray
b = np.array([6,7,8])
b
type(b)

b = np.array([(1,2,3),(1,2,3)])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [2]:
# 创建常规数组
np.zeros((6,5))

np.ones((2,3,4),dtype=np.int16)

np.empty((7,4),dtype=np.int16)

np.arange(10,30,5)

np.arange(0,10,0.2)

# 使用linspace 避免精度问题
from numpy import pi
np.linspace(0,2,9)
x = np.linspace(0,2*pi,100)
x
f = np.sin(90)
f

0.8939966636005579

In [55]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

c = a - b 
c

b**2

10*np.sin(a)
a < 35

array([ True,  True, False, False])

In [63]:
# 矩阵乘积
a = np.array([[1,1],[2,3]])
b = np.array([[2,3],[4,5]])
a * b

a @ b

a *= 3
a
b +=a
b

array([[ 5,  6],
       [10, 14]])

In [69]:
b = np.arange(12).reshape(3,4)
b
# b.sum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])